using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace SourceGen
{
    [Generator]
    public class MySourceGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(ctx =>
            {
                var sourceText = @"// <auto-generated/>
namespace GeneratedNamespace
{
    public static class GeneratedClass
    {
        public static string SayHello()
        {
            return ""Hello from generated code!"";
        }
    }
}";
                ctx.AddSource("GeneratedClass.g.cs", SourceText.From(sourceText, Encoding.UTF8));
            });
        }
    }
}
